In [1]:
import torch
import torch.nn.functional as F


def SoftCrossEntropy(inputs, target, reduction='sum'):
    log_likelihood = -F.log_softmax(inputs, dim=1)
    batch = inputs.shape[0]
    if reduction == 'average':
        loss = torch.sum(torch.mul(log_likelihood, target)) / batch
    else:
        loss = torch.sum(torch.mul(log_likelihood, target))
    return loss


In [3]:
pred = torch.tensor([[[[0.2]],[[0.7]],[[0.1]]]])
print(pred.shape)
gt = torch.tensor([[[[0]],[[1]],[[0]]]])
print(gt.shape)
loss = SoftCrossEntropy(pred, gt)
print(loss)
gt_ce = torch.tensor([[[1]]])
print(gt_ce.shape)
loss_ce = F.cross_entropy(pred, gt_ce)
print(loss_ce)

torch.Size([1, 3, 1, 1])
torch.Size([1, 3, 1, 1])
tensor(0.7679)
torch.Size([1, 1, 1])
tensor(0.7679)


In [10]:
import numpy as np
img = np.array([0,1,2])
print(img.shape)
img = np.identity(3)[img]
print(img)

(3,)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
import pandas as pd
import os.path as osp
def _get_ids(ids_csv):
    return pd.read_csv(ids_csv)['name'].tolist() if ids_csv and osp.exists(ids_csv) else None

In [15]:
def repeat_ids(ids):
    seen = set()
    duplicated = set()
    for i in ids:
        if i not in seen:
            seen.add(i)
        else:
            duplicated.add(i)
    return duplicated

In [20]:
import os
path = '/data/data/semi_compete/clip/unlabeled_train/pseudo/mask'
names = os.listdir(path)
print(len(names))
unlabelded_ids = _get_ids('/data/data/semi_compete/clip/unlabeled_train/512_128/pseudo.csv')
# for ids in unlabelded_ids:
#     name = ids.split('/')[-1][:-4]+'.npy'
#     if name not in names:
#         print(name)

unlabeled_names = []
for ids in unlabelded_ids:
    unlabeled_names.append(ids.split('/')[-1][:-4]+'.npy')
for name in names:
    if name not in unlabeled_names:
        print(name)



28725
delete_56-2013-0212-6746-LA93-0M50-E080_1625.npy
delete_56-2013-0212-6746-LA93-0M50-E080_1645.npy
delete_56-2013-0212-6746-LA93-0M50-E080_1635.npy
delete_29-2012-0124-6840-LA93-0M50-E080_1065.npy
delete_29-2012-0124-6840-LA93-0M50-E080_1060.npy
delete_29-2012-0124-6831-LA93-0M50-E080_2345.npy
delete_56-2013-0212-6746-LA93-0M50-E080_1640.npy
delete_56-2013-0212-6746-LA93-0M50-E080_1630.npy
delete_29-2012-0124-6840-LA93-0M50-E080_1070.npy
